# Willkommen in Julia!

**Julia** ist eine der schönsten real existierenden Programmiersprachen. Wir nutzen sie mit dem Editor **Jupyterlab**, der uns die Ergebnisse sofort ausgibt (ähnlich wie in _Mathematica_ oder _Mupad_). Das ist super, um die Sprache zu lernen! Wir können mit den Tasten `a` bzw `b` einen neuen Input-Block unter bzw über dem derzeit ausgewählten erstellen und dort `2+2` ausrechnen. (Beachte, dass du nicht gerade _dieses_ Fenster hier editierst. Den Editiermodus verlässt du mit `Escape`. Du betrittst den Editiermodus mit `Enter`.) Den ausgewählten Block änderst du mit den _Pfeiltasten_.  Du berechnest ein Codefeld, indem du  es auswählst und `Shift+Enter` drückst. Probiere es ruhig selbst aus:

In [2]:
2+2

4

In [3]:
sum(1/n^2 for n=1:1000)

1.6439345666815615

Faszinierend! Julia-Code sieht (zumindest oberflächlich) aus wie eine Mischung aus _Matlab_ und _Python_. Das schöne daran ist, dass viele Definitionen im Prinzip fast genauso aussehen, wie wenn man sie auf einer Tafel aufschreiben würde. Wollen wir etwa die Matrix $A$
definieren mit Einträgen
$$A_{ij} = i+n\cdot (j-1) \qquad \forall{i=1,\ldots,n, j=1,\ldots,n} $$
so können wir schreiben:

In [4]:
n = 4;
A = [i + n*(j-1) for i=1:n,j=1:n]

4×4 Array{Int64,2}:
 1  5   9  13
 2  6  10  14
 3  7  11  15
 4  8  12  16

Die Sprache **Julia** und der Editor **Jupyterlab** sind zwei unabhängige Bestandteile unseres Kurses. Man kann Jupyterlab auch mit anderen Sprachen verwenden, genauso wie man Julia auch als reine Kommandozeilenanwendung ohne Editor nutzen kann. Das würde ich für Anfänger jedoch nicht empfehlen.

$\newcommand{\Q}{\mathbb{Q}}
\newcommand{\R}{\mathbb{R}}
\newcommand{\C}{\mathbb{C}}
\newcommand{\N}{\mathbb{N}}
\newcommand{\Sn}{\mathbb{S}^{n-1} }
\newcommand\Z{\mathbb Z}$Aber **Jupyterlab** kann noch mehr als nur Code ausführen:
1. Mit `m` änderst du den Modus eines Eingabefelds von _Code_ zu _Markdown_. In Markdown kannst du deine Gedanken mit einer _einfachen_, aber **ausdrucksstarken** Formatierung niederschreiben . Denke immer daran: Jeder Code ist nur so gut wie seine Dokumentation! Wann immer du am Rechner Experimente ausführst, solltest du auch zugleich aufschreiben, was du dir dabei gedacht ~~(oder auch nicht gedacht)~~ hast. So weißt du auch in einigen Wochen noch, was du eigentlich tun wolltest!
2. In _Markdown_-Feldern können wir **Latex** nutzen: Sei $G = (V,E)$ ein Graph mit Knotenmenge $V = \{1,\ldots, n\}$ für ein $n\in \N$. Wir fassen $E\in \{0,1\}^{n \times n} $ als _symmetrische Matrix_ auf. Dies ist die sogenannte _Adjazenzmatrix_ von $G$, welche die Kantenrelation beschreibt.

Es gibt noch zahlreiche weitere [Jupyterlab-Shortcuts](https://blog.ja-ke.tech/assets/jupyterlab-shortcuts/Shortcuts.pdf). Wir wollen nun die Eigenwerte eines _zufälligen gleichverteilten Graphen_, d.h. mit Adjazenzmatrix $E\sim \{0,1\}^{n \times n} $, berechnen.

In [14]:
n = 6;
A = rand(n,n) # random matrix with entries in [0,1]
E = [Int(round(a, digits=0)) for a in A] # note: E is not yet symmetric!

6×6 Array{Int64,2}:
 1  0  1  1  1  0
 0  0  0  0  1  0
 1  0  0  0  1  1
 0  0  1  0  1  1
 0  0  0  0  1  0
 1  0  1  1  0  0

Übrigens: Will man zufällige Einträge in $\{0,1\}$ statt $[0,1]$,  kann man genauso gut auch schreiben:  
`E = [rand(0:1) for i=1:n, j=1:n]`  
Oder noch kürzer:  
`E = rand(0:1, n,n)`  
Wie man sieht führen viele Wege nach Rom...  

Nun müssen wir unsere Matrix aber noch symmetrisch machen:

In [15]:
lowertriag = [i > j for i=1:n, j=1:n] # this is how we get the strictly lower triagonal 
uppertriag = [i < j for i=1:n, j=1:n] # likewise

6×6 Array{Bool,2}:
 0  1  1  1  1  1
 0  0  1  1  1  1
 0  0  0  1  1  1
 0  0  0  0  1  1
 0  0  0  0  0  1
 0  0  0  0  0  0

In [16]:
# die praktische Listennotation funktioniert sogar mit Zuweisungen.
[E[i,j] = E[j,i] for i=1:n,j=1:n if i> j ]
[E[i,j] = 0      for i=1:n,j=1:n if i==j ]
E



6×6 Array{Int64,2}:
 0  0  1  1  1  0
 0  0  0  0  1  0
 1  0  0  0  1  1
 1  0  0  0  1  1
 1  1  1  1  0  0
 0  0  1  1  0  0

Streng genommen ist das hier nicht besonders effizient: Wir haben erst eine volle Matrix ausgewürfelt, um dann etwa die Hälfte der Einträge zu verwerfen. Das kannst du gerne optimieren, wenn du es hinkriegst!

Die Eigenwerte der Adjazenzmatrix eines Graphen tragen oftmals nützliche _globale_ Informationen über die _Struktur des Graphen_. Der genaue Zusammenhang zwischen dem Graphen und seinen Eigenwerten ist für uns aktuell noch mysteriös und wird im Laufe der Vorlesung hoffentlich etwas klarer werden. Für den Moment begnügen wir uns damit, die Eigenwerte unserer Adjazenzmatrix zu berechnen und zu bewundern.  Hierfür müssen wir das erste Mal ein **Paket einbinden**. Dieses hier ist in Julia standardmäßig schon installiert, daher reicht es, Julia zu sagen, dass wir es benutzen wollen:

In [17]:
using LinearAlgebra # we need a package to compute eigenvalues
eigvals(E)

6-element Array{Float64,1}:
 -2.2403421067592486
 -1.3683708672043942
 -3.211546358915673e-17
  2.670573269090226e-16
  0.664833834674929
  2.9438791392887116

Kleiner Reality-Check, um zu sehen, ob wir groben Unsinn ausgerechnet haben:

In [18]:
tr(E) # ist Null 

0

In [19]:
sum(eigvals(E)) # sollte theoretisch auch Null sein, aber Numerik...

-1.7763568394002505e-15

### Ein etwas anspruchsvolleres Beispiel: $d$-reguläre Graphen

Wir konstruieren nun einen _$d$-regulären_ Graphen $G$. Das soll heißen: Jeder Knoten von $G$ ist mit genau $d$ anderen Knoten verbunden. Leider enthält der Code einen _subtilen_, aber **bösartigen** Fehler. Finde ihn **oder** schreibe von Grund auf einen besseren! :)

In [22]:
E = [0 for i=1:n,j=1:n];
d = 3; # e.g. let G be 3-regular


# for each node v we choose d entries from the column belonging to v
function chooseEntriesFrom(v, numEntries) 
    result = [];
    for k in 1:numEntries
        availEntries = [i for i in v if !(i in result)];
        if isempty(availEntries)
            return result;
        end
        # man beachte das Ausrufezeichen hinter append: Es weist darauf hin, dass append! das Array "result" verändert, statt ein neues zu erstellen. 
        append!(result, availEntries[rand(1:length(availEntries))]); 
    end 
    return result;
end

# then, do this for all nodes:
for j=1:n
    idx = chooseEntriesFrom([i for i=j:n if i!=j],d-sum(E[1:j,j]));
    print(idx);
    E[idx,j] .= 1;
    E[j,idx] .= 1;
end
E

# Übung für dich: Dieser Code ist hässlich. Kannst du einen schöneren und richtigeren Code schreiben?

Any[4, 3, 6]Any[4, 3, 5]Any[5]Any[6]Any[6]Any[]

6×6 Array{Int64,2}:
 0  0  1  1  0  1
 0  0  1  1  1  0
 1  1  0  0  1  0
 1  1  0  0  0  1
 0  1  1  0  0  1
 1  0  0  1  1  0

In [23]:
eigvals(E)

6-element Array{Float64,1}:
 -2.0000000000000004
 -1.9999999999999998
 -3.210477034487543e-16
  1.3828883856350504e-16
  1.0000000000000004
  3.0

Lösung: Der Code kann in eine _Sackgasse_ laufen, bei der die Knoten ausgehen, bevor jeder Knoten drei Partner hat.

**Beachte:** Wenn der Graph regulär ist, dann ist sein _größter Eigenwert_ immer die _Regularität_ des Graphen, in diesem Fall also 3. 
Du kannst den Code oben ein paar Mal durchführen, bist du eine 3-reguläre Adjazenzmatrix erhältst, und diesen Sachverhalt für dich selbst verifizieren. 

>Hast du eine Idee, wieso das gelten könnte? Was könnte ein zugehöriger Eigenvektor sein? Finde diese Antwort entweder durch **Nachdenken** oder, indem du den Befehl für die Eigenvektoren in [Julias Dokumentation](https://docs.julialang.org/en/v1/search/?q=) suchst.


### Polynome in Julia

Zum Abschluss wollen wir noch ein bisschen mit **Polynomen** spielen. Lasst uns dazu erst das zugehörige Paket herunterladen. Der Code für die Installation muss nur einmal ausgeführt werden, daher ist er Standardmäßig auskommentiert.

In [ ]:
# import Pkg; Pkg.add("MultivariatePolynomials"); 

Der nun folgende Code schreibt eine ganz allgemeine quadratische Form auf, deren Koeffizienten **Variablen** sind.

In [24]:
using DynamicPolynomials
@polyvar X[1:n];
X*transpose(X)
idx = [LinearIndices(zeros(n,n))[i,j] for i=1:n,j=1:n];
@polyvar G[idx]; 
transpose(X)*G*X

X₁²G₁ + X₁X₂G₂ + X₁X₂G₇ + X₁X₃G₃ + X₁X₃G₁₃ + X₁X₄G₄ + X₁X₄G₁₉ + X₁X₅G₅ + X₁X₅G₂₅ + X₁X₆G₆ + X₁X₆G₃₁ + X₂²G₈ + X₂X₃G₉ + X₂X₃G₁₄ + X₂X₄G₁₀ + X₂X₄G₂₀ + X₂X₅G₁₁ + X₂X₅G₂₆ + X₂X₆G₁₂ + X₂X₆G₃₂ + X₃²G₁₅ + X₃X₄G₁₆ + X₃X₄G₂₁ + X₃X₅G₁₇ + X₃X₅G₂₇ + X₃X₆G₁₈ + X₃X₆G₃₃ + X₄²G₂₂ + X₄X₅G₂₃ + X₄X₅G₂₈ + X₄X₆G₂₄ + X₄X₆G₃₄ + X₅²G₂₉ + X₅X₆G₃₀ + X₅X₆G₃₅ + X₆²G₃₆

 Häufig ist es auch interessant zu wissen, wie man ein Polynom **linearisiert**, das heißt, alle Monome durch neue Variablen ersetzt. In Julia ist das sehr einfach:

In [26]:
# alle Monome von Grad 2 
deg2mons = unique(X*transpose(X));
# bzw allgemeiner alle Monome von Grad d (hier d = 2) in X mit vorgefertigter Funktion
d = 2;
mon = monomials(X,d)

# linearisiere den Monomvektor: Jedes Monom wird durch eine neue Variable ersetzt.
@polyvar G[1:length(mon)] 

# linearisiert ein homogenes Polynom p vom Grad d
function linearize(poly)
    # w = monomials(poly);
    G_sel = [G[i] for i in 1:length(G) if mon[i] in monomials(poly)]
    return transpose(G_sel)*coefficients(poly)
end

# some arbitrary form of degree 2
p = sum((X[i]+X[j])*X[i] for i=1:n,j=1:n);
p

#linearize(X[1]^2 + X[2]^2);
linearize(p)


# Übung: Überlege dir, ob dieser Code auch für Polynome funktioniert, in denen nicht alle Monome von Grad 2 auftauchen! Wieso bzw. wieso nicht? 

7G₁ + 2G₂ + 2G₃ + 2G₄ + 2G₅ + 2G₆ + 7G₇ + 2G₈ + 2G₉ + 2G₁₀ + 2G₁₁ + 7G₁₂ + 2G₁₃ + 2G₁₄ + 2G₁₅ + 7G₁₆ + 2G₁₇ + 2G₁₈ + 7G₁₉ + 2G₂₀ + 7G₂₁

#### Operationen auf den Koeffizienten



In [17]:
2.5p

transpose(monomials(2.5p))*[Int(i) for i in coefficients(round(2.5p)) ]

18X₁² + 5X₁X₂ + 5X₁X₃ + 5X₁X₄ + 5X₁X₅ + 5X₁X₆ + 18X₂² + 5X₂X₃ + 5X₂X₄ + 5X₂X₅ + 5X₂X₆ + 18X₃² + 5X₃X₄ + 5X₃X₅ + 5X₃X₆ + 18X₄² + 5X₄X₅ + 5X₄X₆ + 18X₅² + 5X₅X₆ + 18X₆²

#### Substitution

In [27]:
using DynamicPolynomials
A = rand(n, n)
p = sum(X .* X) # X_1^2 + X_2^2 + ... + X_n^2
subs(p, X[1]=>2, X[3]=>3)

X₂² + X₄² + X₅² + X₆² + 13

In [20]:
p(X=>A*vec(X)) # corresponds to dot(A*x, A*x), need vec to convert the tuple to a vector

2.5235243296849434X₁² + 4.529079314269755X₁X₂ + 2.658650132120613X₁X₃ + 2.851487825489705X₁X₄ + 4.638064829621721X₁X₅ + 3.097052158890456X₁X₆ + 2.376064952382795X₂² + 3.0124556667436875X₂X₃ + 2.8828213493551917X₂X₄ + 4.234601714973445X₂X₅ + 2.8835701795131676X₂X₆ + 1.5350577680410147X₃² + 2.4312892681358855X₃X₄ + 3.2933244663987713X₃X₅ + 1.6071570898042302X₃X₆ + 2.9970047397157304X₄² + 4.471567216744107X₄X₅ + 2.2123895739032133X₄X₆ + 2.8611809786753195X₅² + 2.96648390455783X₅X₆ + 0.9955853095065348X₆²